---
- name: Manage system groups for '{{ inventory_hostname }}'
  ansible.builtin.group:
    name: "{{ item.name }}"
    gid: "{{ item.gid | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  when: system_groups
  loop: "{{ system_groups }}"

- name: Manage system users for '{{ inventory_hostname }}'
  ansible.builtin.user:
    name: "{{ item.username }}"
    comment: "{{ item.comment | default(omit) }}"
    password: "{{ item.password }}"
    groups: "{{ item.groups | default(omit) }}"
    shell: "{{ item.shell | default(omit) }}"
    append: "{{ item.append | default('no') }}"
    remove: "{{ item.remove | default('no') }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ system_users }}"

- name: Manage SSH authorized keys
  include_tasks: keys.yml
  vars:
    - username: "{{ current_user.username }}"
    - keys: "{{ current_user.authorized_keys }}"
  when: current_user.authorized_keys
  loop: "{{ system_users }}"
  loop_control:
    loop_var: current_user
